/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChatSessionidImport } from './routes/chat.$session_id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChatSessionidRoute = ChatSessionidImport.update({
  id: '/chat/$session_id',
  path: '/chat/$session_id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat/$session_id': {
      id: '/chat/$session_id'
      path: '/chat/$session_id'
      fullPath: '/chat/$session_id'
      preLoaderRoute: typeof ChatSessionidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat/$session_id': typeof ChatSessionidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat/$session_id': typeof ChatSessionidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chat/$session_id': typeof ChatSessionidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat/$session_id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat/$session_id'
  id: '__root__' | '/' | '/chat/$session_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatSessionidRoute: typeof ChatSessionidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatSessionidRoute: ChatSessionidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat/$session_id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat/$session_id": {
      "filePath": "chat.$session_id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
